### ISSUE TITLE
Data Table Sorting issues - Custom and edge case handling

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#591]
**Data Table Sorting issues**
Sorting the data tables does not work properly in some edge cases and with arrays containing objects.

**Linked issues**
- [x] https://github.com/bancorprotocol/webapp/issues/587
- [x] https://github.com/bancorprotocol/webapp/issues/571
- [x] https://github.com/bancorprotocol/webapp/issues/566

**Proposed solution**
- [x] Add functionality for custom sorting functions passed as prop to `DataTable.vue` component
- [x] Add custom sorting functions for specific tables and columns. 

This will require defined sorting rules for each table and specific columns. Then custom implementation of those rewuired.
eg: Protected Table -> APR column: Should that column be sorted by `1 Day` or `1 Week` value?

**Comment by pingustar** [comment]
DataTable takes now an optional sort function prop. The default sort is improved as well to detect if strings are numbers, and it puts n/a values at the end. There is also a defaultTableSort function that can be used when building custom sorting, eg: if you want to include Zeros in the sorting. This is useful for ascending order, so we dont have 20 pages with zero values.

**Comment by Velua** [comment]
I imagine this should be assigned to you then.

**Comment by pingustar** [comment]
Table sorting is updated. Should work throughout the app now.

Please reopen if you find any inconsistency.
