### ISSUE TITLE
EPIC - Sentry Error Handling

### ISSUE THREAD

**Issue by pingustar** [bancorprotocol/webapp#999]
Collection of Topics that need to be addressed regarding Sentry.io

### Main Objective
- [ ] Improve error handling (try, catch, throw). 
- [ ] Improve error tracking and monitoring using Sentry. 
- [ ] Cleanup unused console logs

### Sentry Bot Reports
- [ ] #466 
- [ ] #468 
- [ ] #469 
- [ ] #796 

### Stale/Closed Issues
- [ ] #501 
- [ ] #795
